### ISSUE TITLE
expose sentRequestAtMillis receivedResponseAtMillis to calculate latency

### ISSUE THREAD

**Issue by ComLock** [enonic/lib-http-client#18]
Perhaps even calculate and make latency available?

I guess we do not want to slow down every request if that is the result?

**Comment by aro** [comment]
This should be a small change. The OkHttp Java library we use has those properties, we just need to expose them, or substract them and set it as latency.

**Comment by rymsha** [comment]
After  #89 there is no OkHttp. 
library uses Trace XP API and can give a clue how long it took to receive a response. Isn't in sufficient?

**Comment by ComLock** [comment]
What is Trace XP API, where is it documented? JS?

**Comment by rymsha** [comment]
It is a Java API. Resulted used by https://github.com/enonic/app-livetrace/blob/master/docs/index.adoc
