### ISSUE TITLE
Docs easly misunderstood

### ISSUE THREAD

**Issue by gbbirkisson** [enonic/lib-http-client#63]
The example how to use certificate is easily misunderstood. https://github.com/enonic/lib-http-client/blob/master/docs/index.adoc#using-custom-certificate

```
var certificates = app.config['certificates']; // Certificate stored in the application config file
```

This is the misunderstanding. People do not often put their certs in the configuration files, but rather point to a file where the certificate is.

We need to be more explicit what is going on in this example.

**Comment by rymsha** [comment]
fixed in https://github.com/enonic/lib-http-client/pull/82
